services:

  homeowners.proxy:
    image: nginx
    container_name: homeowners-dev-proxy
    hostname: local-dev.homeowners.com
    ports: 
      - 443:443
    depends_on:
      homeowners.web.api:
        condition: service_started
    volumes:
      - ./proxy-config:/etc/nginx/conf.d
      # - ./Certificates:/etc/nginx/cert

  homeowners.web.api:
    image: ${DOCKER_REGISTRY-}homeownerswebapi
    container_name: homeowners-dev-api
    build:
      context: ./../../
      dockerfile: API/HomeOwners.Web.API/Dockerfile
    volumes:
      - ./../../dev/DockerCompose/Config:/_config
      - ./dev-keys:/keys
    environment:
      - HomeOwnersConfigurationPath=/_config/api-configuration.json
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
 
  homeowners.web.ui:
    image: ${DOCKER_REGISTRY-}homeownerswebui
    container_name: homeowners-dev-ui
    build:
      context: ./../../
      dockerfile: Frontend/HomeOwners.Web.UI/Dockerfile
    volumes:
      - ./../../dev/DockerCompose/Config:/_config
      - ./dev-keys:/keys
    environment:
      - HomeOwnersConfigurationPath=/_config/web-configuration.json
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development

  opensearch-node1: 
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - ./OpenSearchData/opensearch-data1:/usr/share/opensearch/data 
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer

  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./OpenSearchData/opensearch-data2:/usr/share/opensearch/data

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
      # SERVER_PORT: 5601 # Default value
      OPENSEARCHDASHBOARDS_AUTOCOMPLETETIMEOUT: 900000
      OPENSEARCHDASHBOARDS_AUTOCOMPLETETERMINATEAFTER: 900000000
    depends_on:
      opensearch-node1:
        condition: service_started
      opensearch-node2:
        condition: service_started